server:
  port: 8080
spring:
  #邮箱发送消息
  mail:
    host: smtp.qq.com
    username: 2982419675@qq.com
    password: asdlqdpqurpiddbf
    to: 1270392431@qq.com
  #应用名称
  application:
    name: reggie_take_out
  #数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "123456"
  #redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0

#mybatisPlus
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID  #雪花算法形成id

#图片资源存放位置
reggin:

#  path: src\main\resources\img\
#  path: D:\Desktop\Java学习\reggie_take_outsrc\main\resources\img\
  path: src\main\resources\img\



#  path:  /root/zsj_data/img/  #linux系统下
#  path:  usr/local/img    #linux系统下

